name: textmining-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - beautifulsoup4=4.9.*
  - conda-forge::blas=*=openblas
  - bokeh=2.1.*
  - bottleneck=1.3.*
  - cython=0.29.*
  - dask=2.20.*
  - dill=0.3.*
  - h5py=2.10.*
  - hdf5=1.10.*
  - ipywidgets=7.5.*
  - ipympl=0.5.7
  - jupyterlab=2.2.6
  - matplotlib-base=3.2.*
  - nb_conda
  - nodejs
  # numba update to 0.49 fails resolving deps.
  - numba=0.48.*
  - numexpr=2.7.*
  - pandas=1.1.*
  - patsy=0.5.*
  - pip 
  - protobuf=3.12.*
  - pylint
  - pytables=3.6.*
  - scikit-learn=0.23.*
  - scipy=1.5.*
  - seaborn=0.10.*
  - sqlalchemy=1.3.*
  - statsmodels=0.11.*
  - spacy >=2.2.0,<3.0.0
  - spacy-lookups-data
  - sympy=1.6.*
  - vincent=0.4.*
  - voila=0.1.21
  - widgetsnbextension=3.5.*
  - wordcloud
  - xlrd=1.2.*
  - pip:
    - pyarrow
    - streamlit
    - https://github.com/explosion/spacy-models/releases/download/es_core_news_sm-2.3.1/es_core_news_sm-2.3.1.tar.gz
    - https://github.com/explosion/spacy-models/releases/download/es_core_news_md-2.3.1/es_core_news_md-2.3.1.tar.gz
    - https://github.com/explosion/spacy-models/releases/download/es_core_news_lg-2.3.1/es_core_news_lg-2.3.1.tar.gz